const FALLBACK_DESTINATIONS = [
  {
    id: 'singapore',
    status: 'unlocked',
    title: 'Chapter I',
    subtitle: 'The Garden City',
    emoji: '🦁',
    hint: null,
    gallery: [
      { src: 'images/singapore/01.jpg', alt: 'Marina Bay skyline at dusk', caption: 'Where the bay meets the sky' },
      { src: 'images/singapore/02.jpg', alt: 'Gardens by the Bay Supertrees', caption: 'Trees that glow at night' },
      { src: 'images/singapore/03.jpg', alt: 'Hawker centre food spread', caption: 'A table worth the queue' },
      { src: 'images/singapore/04.jpg', alt: 'Chinatown shophouses', caption: 'Colors on every corner' },
      { src: 'images/singapore/05.jpg', alt: 'Merlion fountain', caption: 'The icon everyone finds first' },
      { src: 'images/singapore/06.jpg', alt: 'Little India street', caption: 'Spices in the air' },
      { src: 'images/singapore/07.jpg', alt: 'Sentosa beach sunset', caption: 'Golden hour by the shore' },
      { src: 'images/singapore/08.jpg', alt: 'Haji Lane murals', caption: 'Walls that tell stories' },
      { src: 'images/singapore/09.jpg', alt: 'Night market lights', caption: 'The city that never sleeps early' },
      { src: 'images/singapore/10.jpg', alt: 'Botanic Gardens path', caption: 'Green in the middle of glass' },
      { src: 'images/singapore/11.jpg', alt: 'Kampong Glam mosque', caption: 'Gold dome, quiet heart' },
      { src: 'images/singapore/12.jpg', alt: 'MRT station architecture', caption: 'Underground, always on time' },
      { src: 'images/singapore/13.jpg', alt: 'Satay by the river', caption: 'Smoke and peanut sauce' },
      { src: 'images/singapore/14.jpg', alt: 'Jewel Changi waterfall', caption: 'Rain indoors, on purpose' },
      { src: 'images/singapore/15.jpg', alt: 'East Coast Park cycling', caption: 'Wind in your hair' },
      { src: 'images/singapore/16.jpg', alt: 'Clarke Quay at night', caption: 'Neon reflected on water' },
      { src: 'images/singapore/17.jpg', alt: 'MacRitchie treetop walk', caption: 'Above the canopy' },
      { src: 'images/singapore/18.jpg', alt: 'Kaya toast breakfast', caption: 'Soft eggs, strong kopi' },
    ],
  },
  {
    id: 'locked-01',
    status: 'locked',
    title: 'Chapter II',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Where trains pierce through towers, white coffee steams at dawn, and limestone cliffs hide temples older than memory.',
    teaser: 'Train · Coffee · Caves',
    gallery: null,
  },
  {
    id: 'locked-02',
    status: 'locked',
    title: 'Chapter III',
    subtitle: '???',
    emoji: '🔒',
    hint: 'A vertical city wrapped in fog, where the railway disappears into someone\'s living room and the spice burns twice.',
    teaser: 'Fog · Monorail · Fire',
    gallery: null,
  },
  {
    id: 'locked-03',
    status: 'locked',
    title: 'Chapter IV',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Powder dreams beneath sacred peaks. After the descent, steam rises from cedar baths while snow falls without sound.',
    teaser: 'Powder · Onsen · Silence',
    gallery: null,
  },
  {
    id: 'locked-04',
    status: 'locked',
    title: 'Chapter V',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Roads that feel borrowed from a fantasy map. Emerald hills, sheep outnumber people, and the ocean carved fjords into the land.',
    teaser: 'Road · Fjord · Middle-earth',
    gallery: null,
  },
  {
    id: 'locked-05',
    status: 'locked',
    title: 'Chapter VI',
    subtitle: '???',
    emoji: '🔒',
    hint: 'When green fire dances across a black sky and the sun refuses to set, you\'ll understand why Vikings looked up and believed.',
    teaser: 'Aurora · Fjord · Midnight',
    gallery: null,
  },
  {
    id: 'locked-06',
    status: 'locked',
    title: 'Chapter VII',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Ice skates carve circles beneath a tower of lights. Yellow cabs honk through winter magic on avenues that never sleep.',
    teaser: 'Skates · Tree · Taxi',
    gallery: null,
  },
  {
    id: 'locked-07',
    status: 'locked',
    title: 'Chapter VIII',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Millions walk the same circle around an ancient cube. The call echoes at dawn across a desert that holds the holiest square on earth.',
    teaser: 'Pilgrimage · Cube · Dawn',
    gallery: null,
  },
  {
    id: 'locked-08',
    status: 'locked',
    title: 'Chapter IX',
    subtitle: '???',
    emoji: '🔒',
    hint: 'When the rains come, heaven falls to earth. The sky mirrors itself across endless white salt at 3,600 meters above the sea.',
    teaser: 'Mirror · Salt · Altitude',
    gallery: null,
  },
  {
    id: 'locked-09',
    status: 'locked',
    title: 'Chapter X',
    subtitle: '???',
    emoji: '🔒',
    hint: 'Golden waves swallow the horizon. Caravans cross dunes that shift every night, and stars feel close enough to touch.',
    teaser: 'Dunes · Caravan · Stars',
    gallery: null,
  },
  {
    id: 'locked-10',
    status: 'locked',
    title: 'Final Chapter',
    subtitle: '???',
    emoji: '🔒',
    hint: 'At the end of all maps, penguins march in formation and icebergs calve with a sound like thunder. No flag claims this place.',
    teaser: 'Penguin · Ice · End of Map',
    gallery: null,
  },
];
